_wandb:
    value:
        cli_version: 0.23.0
        e:
            w46q71nbihvpyjku4beyxmj6i9mavam9:
                args:
                    - configs\settings.yaml
                codePath: bsort\train.py
                codePathLocal: bsort\train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2000397791232"
                        used: "83424010240"
                email: john.doney18@gmail.com
                executable: C:\Users\John\miniconda3\envs\adamata\python.exe
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-5c2fbfdf-0ce8-59e4-1571-959465e74cca
                host: DESKTOP-2TULHT3
                memory:
                    total: "33685835776"
                os: Windows-10-10.0.26200-SP0
                program: D:\john\interview\adamata\bottlecap-color-detection\bsort\train.py
                python: CPython 3.9.25
                root: D:\john\interview\adamata\bottlecap-color-detection
                startedAt: "2025-11-25T08:38:14.938029Z"
                writerId: w46q71nbihvpyjku4beyxmj6i9mavam9
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.25
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch:
    value: 8
class_names:
    value:
        - light_blue
        - dark_blue
        - others
conf:
    value: 0.3
data:
    value: configs/data.yaml
degrees:
    value: 10
device:
    value: 0
epochs:
    value: 500
fliplr:
    value: 0.5
flipud:
    value: 0.5
hsv_h:
    value: 0.015
hsv_s:
    value: 0.7
hsv_v:
    value: 0.4
imgsz:
    value: 320
iou:
    value: 0.45
lr0:
    value: 0.001
mixup:
    value: 0.5
model:
    value: yolov8n-p2.pt
model_path:
    value: runs/detect/train2/weights/best.pt
mosaic:
    value: 1
name:
    value: exp2
optimizer:
    value: auto
output_dir:
    value: inference_results
patience:
    value: 50
perspective:
    value: 0
project:
    value: bottle_caps
save_period:
    value: 50
scale:
    value: 0.5
seed:
    value: 0
shear:
    value: 0
translate:
    value: 0.1
workers:
    value: 4
